apiVersion: v1
kind: Pod
metadata:
  name: appblue
  labels:
    app: appblue
spec:
  containers:
    - image: "httpd"
      name: httpd
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: appblue
spec:
  selector:
    app: appblue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appblue
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: "blue.example.com"
      http:
        paths:
          - path: /
            backend:
              service:
                name: appblue
                port:
                  number: 80
            pathType: Exact
